name: tf-ss-env
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - flask
  - jupyterlab
  - pip
  - pip:
      - tensorflow==2.20.0
      - keras-tuner==1.4.6
      - opencv-python==4.12.0.88
      - pillow==10.1.0
      - emnist
